## Memory Spaces - Power Iteration - SOLUTION

### Table of Contents
1. [Introduction to Memory Spaces](#1-introduction-to-memory-spaces)
2. [The CPU Baseline (NumPy)](#2-the-cpu-baseline-numpy)
3. [The GPU Port (CuPy)](#3-the-gpu-port-cupy)
4. [Optimizing Data Generation](#4-optimizing-data-generation)
5. [Verification and Benchmarking](#5-verification-and-benchmarking)
6. [Extra Credit](#extra-credit)

---

### 1. Introduction to Memory Spaces

Before we implement algorithms on the GPU, we must understand the hardware architecture. A heterogeneous system (like the one you are using) consists of two distinct memory spaces:

1. **Host Memory:** Accessible by the CPU.
2. **Device Memory:** Accessible by the GPU.

To ensure data is accessible from a particular processor, we need to explicity transfer it:

* **Host $\to$ Device:** Move data to the GPU to compute.
    * Syntax: `x_device = cp.asarray(x_host)`
* **Device $\to$ Host:** Move results back to the CPU to save to disk, plot with Matplotlib, or print.
    * Syntax: `y_host = cp.asnumpy(y_device)`

#### Implicit Transfers and Synchronization

It is crucial to understand when CuPy interacts with the CPU implicitly. These interactions can kill performance because they force the GPU to pause (synchronize) while data moves.

CuPy silently transfers and synchronizes when you:
1.  **Print** a GPU array (`print(gpu_array)`).
2.  **Convert** to a Python scalar (`float(gpu_array)` or `.item()`).
3.  **Evaluate** a GPU scalar in a boolean context (`if gpu_scalar > 0:`).

#### The Task
To understand the implications of these concepts, let's experiment with estimating the dominant eigenvalue of a matrix using the **Power Iteration** algorithm.

Before we dive into the code, let's understand the math behind the algorithm we are implementing.

**Power Iteration** is a classic iterative method used to find the dominant eigenvalue (the eigenvalue with the largest absolute value) and its corresponding eigenvector of a square matrix $A$.

##### How It Works

The core idea is simple: if you repeatedly multiply a vector by a matrix $A$, the vector will eventually converge towards the dominant eigenvector of $A$, regardless of the initial vector you started with (provided the initial vector has some component in the direction of the dominant eigenvector).

##### The Mathematical Steps

Given a square matrix $A$ and a random initial vector $x_0$, the algorithm proceeds as follows for each step $k$:

**1. Matrix-Vector Multiplication:**

We calculate the next approximation of the vector:

$$y = A x_k$$

**2. Eigenvalue Estimation (Rayleigh Quotient):**

We estimate the eigenvalue $\lambda$ using the current vector. This is essentially projecting $y$ onto $x$:

$$\lambda_k = \frac{x_k^T y}{x_k^T x_k} = \frac{x_k^T A x_k}{x_k^T x_k}$$

**3. Residual Calculation (Error Check):**

We check how close we are to the true definition of an eigenvector ($Ax = \lambda x$) by calculating the "residual" (error):

$$r = ||y - \lambda_k x_k||$$

If $r$ is close to 0, we have converged.

**4. Normalization:**

To prevent the numbers from exploding (overflow) or vanishing (underflow), we normalize the vector for the next iteration:

$$x_{k+1} = \frac{y}{||y||}$$

We will start with a standard CPU implementation, port it to the GPU using CuPy, and analyze the performance impact of memory transfers.


In [1]:
import numpy as np
import cupy as cp
import cupyx as cpx
import time
from dataclasses import dataclass

# Configuration for the algorithm
@dataclass
class PowerIterationConfig:
    dim: int = 4096                    # Matrix size (dim x dim)
    dominance: float = 0.1             # How much larger the top eigenvalue is (controls convergence, higher == faster)
    max_steps: int = 400               # Maximum iterations
    check_frequency: int = 10          # Check for convergence every N steps
    progress: bool = True              # Print progress logs
    residual_threshold: float = 1e-10  # Stop if error is below this

### 2. The CPU Baseline (NumPy)

We generate a random dense matrix that is diagonalizable. This data is generated on the **Host (CPU)** and resides in **Host Memory**.


In [2]:
def generate_host(cfg=PowerIterationConfig()):
    """Generates a random diagonalizable matrix on the CPU."""
    np.random.seed(42)

    # Create eigenvalues: One large one (1.0), the rest smaller
    weak_lam = np.random.random(cfg.dim - 1) * (1.0 - cfg.dominance)
    lam = np.random.permutation(np.concatenate(([1.0], weak_lam)))

    # Construct matrix A = P * D * P^-1
    P = np.random.random((cfg.dim, cfg.dim))  # Random invertible matrix
    D = np.diag(np.random.permutation(lam))   # Diagonal matrix of eigenvalues
    A = ((P @ D) @ np.linalg.inv(P))          # The final matrix
    return A

# Generate the data on Host
print("Generating Host Data...")
A_host = generate_host()
print(f"Host Matrix Shape: {A_host.shape}")
print(f"Data Type: {A_host.dtype}")

Generating Host Data...
Host Matrix Shape: (4096, 4096)
Data Type: float64


#### Implementing Power Iteration (CPU)

As described above, the Power Iteration algorithm repeatedly multiplies a vector $x$ by matrix $A$ ($y = Ax$) and normalizes the result. We initialize this algorithm with a vector of 1s ($x_0$) as our initial guess.

In [3]:
def estimate_host(A, cfg=PowerIterationConfig()) -> np.ndarray:
    """
    Performs power iteration using purely NumPy (CPU).
    """
    # Initialize solution vector.
    x = np.ones(A.shape[0], dtype=np.float64)

    for i in range(0, cfg.max_steps, cfg.check_frequency):
        # Matrix-Vector multiplication.
        y = A @ x

        # Rayleigh quotient.
        lam = (x @ y) / (x @ x)

        # Calculate residual (error).
        res = np.linalg.norm(y - lam * x)

        # Normalize vector for next step.
        x = y / np.linalg.norm(y)

        if cfg.progress:
            print(f"Step {i}: residual = {res:.3e}")

        # Save a checkpoint.
        np.savetxt(f"/tmp/host_{i}.txt", x)

        # Convergence check.
        if res < cfg.residual_threshold:
            break

        # Run intermediate steps without checking residual to save compute.
        for _ in range(cfg.check_frequency - 1):
            y = A @ x
            x = y / np.linalg.norm(y)

    return (x.T @ (A @ x)) / (x.T @ x)

lam_est_host = estimate_host(A_host)

assert isinstance(lam_est_host, (np.ndarray, np.generic)), "Must return a NumPy array or NumPy scalar"
np.testing.assert_allclose(lam_est_host, 1, atol=1e-4)

print()
print("Dominant Eigenvalue:", lam_est_host)

Step 0: residual = 7.594e+00
Step 10: residual = 1.699e-02
Step 20: residual = 2.148e-02
Step 30: residual = 1.295e-02
Step 40: residual = 4.494e-03
Step 50: residual = 1.366e-03
Step 60: residual = 4.129e-04
Step 70: residual = 1.274e-04
Step 80: residual = 4.013e-05
Step 90: residual = 1.286e-05
Step 100: residual = 4.181e-06
Step 110: residual = 1.374e-06
Step 120: residual = 4.550e-07
Step 130: residual = 1.517e-07
Step 140: residual = 5.085e-08
Step 150: residual = 1.712e-08
Step 160: residual = 5.785e-09
Step 170: residual = 1.959e-09
Step 180: residual = 6.661e-10
Step 190: residual = 2.271e-10
Step 200: residual = 7.733e-11

Dominant Eigenvalue: 0.9999999999599408


### 3. The GPU Port (CuPy)

#### Exercise: Port the CPU Implementation to GPU

Now it's your turn! Your task is to convert the `estimate_host` function to run on the GPU using CuPy.

**Remember the rules of Memory Spaces:**
1.  **Transfer:** Move `A_host` from CPU to GPU using `cp.asarray()`.
2.  **Compute:** Perform math using `cp` functions on the GPU.
3.  **Retrieve:** Move result back to CPU using `cp.asnumpy()`.

**Hint:** CuPy tries to replicate the NumPy API. In many cases, you can simply change `np.` to `cp.`. However, CuPy operations *must* run on data present in Device Memory.

**The code below starts as a copy of the CPU implementation. Modify it to run on the GPU:**


In [4]:
def estimate_device(A, cfg=PowerIterationConfig()) -> np.ndarray:
    """
    Port the power iteration algorithm to the GPU using CuPy.

    Steps to complete:
    1. Transfer the input matrix A to the GPU
    2. Initialize the vector x on the GPU
    3. Replace np operations with cp operations
    4. Copy x from device to host and save a checkpoint
    5. Return the result as a NumPy array
    """
    # Transfer the input matrix from host to device.
    # If A is on the host, cp.asarray copies it to the GPU.
    # If A is already on the GPU, cp.asarray is a no-op.
    A_gpu = cp.asarray(A)

    # Initialize vector of ones on the device.
    x = cp.ones(A_gpu.shape[0], dtype=cp.float64)

    for i in range(0, cfg.max_steps, cfg.check_frequency):
        # Matrix-Vector multiplication (same as NumPy).
        y = A_gpu @ x

        # Rayleigh quotient (same as NumPy).
        lam = (x @ y) / (x @ x)

        # Calculate residual using cp.linalg.norm.
        res = cp.linalg.norm(y - lam * x)

        # Normalize x using cp.linalg.norm.
        x = y / cp.linalg.norm(y)

        if cfg.progress:
            print(f"Step {i}: residual = {res:.3e}")

        # Transfer x from device to host and save a checkpoint.
        np.savetxt(f"/tmp/device_{i}.txt", cp.asnumpy(x))

        # Convergence check.
        if res < cfg.residual_threshold:
            break

        # Run intermediate steps without checking residual to save compute.
        for _ in range(cfg.check_frequency - 1):
            y = A_gpu @ x
            x = y / cp.linalg.norm(y)

    # Compute result and transfer it from device to host.
    return cp.asnumpy((x.T @ (A_gpu @ x)) / (x.T @ x))

lam_est_device = estimate_device(A_host)

assert isinstance(lam_est_device, (np.ndarray, np.generic)), "Must return a NumPy array or NumPy scalar"
np.testing.assert_allclose(lam_est_device, 1, atol=1e-4)

print()
print("Dominant Eigenvalue:", lam_est_device)

Step 0: residual = 7.594e+00
Step 10: residual = 1.699e-02
Step 20: residual = 2.148e-02
Step 30: residual = 1.295e-02
Step 40: residual = 4.494e-03
Step 50: residual = 1.366e-03
Step 60: residual = 4.129e-04
Step 70: residual = 1.274e-04
Step 80: residual = 4.013e-05
Step 90: residual = 1.286e-05
Step 100: residual = 4.181e-06
Step 110: residual = 1.374e-06
Step 120: residual = 4.550e-07
Step 130: residual = 1.517e-07
Step 140: residual = 5.085e-08
Step 150: residual = 1.712e-08
Step 160: residual = 5.785e-09
Step 170: residual = 1.960e-09
Step 180: residual = 6.659e-10
Step 190: residual = 2.267e-10
Step 200: residual = 7.754e-11

Dominant Eigenvalue: 0.9999999999591407


### 4. Optimizing Data Generation

In the previous step, we generated data on the CPU and copied it to the GPU. For large datasets, the transfer time from host to device can be a bottleneck. 

It is almost always faster to **generate** the data directly on the GPU if possible.

#### Exercise: Generate Data Directly on the GPU

Your task is to convert the `generate_host` function to generate the matrix directly on the GPU using CuPy's random functions.

**Hints:**
- Use `cp.random.seed()` instead of `np.random.seed()`
- Use `cp.random.random()` instead of `np.random.random()`
- Use `cp.random.permutation()` instead of `np.random.permutation()`
- Use `cp.concatenate()`, `cp.array()`, `cp.diag()`, and `cp.linalg.inv()`

**The code below starts as a copy of the CPU implementation. Modify it to generate data directly on the GPU:**


In [5]:
def generate_device(cfg=PowerIterationConfig()):
    """
    Generate a random diagonalizable matrix directly on the GPU.

    This should mirror the generate_host function but use CuPy instead of NumPy.
    The key benefit: no Host->Device transfer needed!
    """
    # ---------------------------------------------------------
    # SOLUTION: Set the random seed on the GPU
    # ---------------------------------------------------------
    cp.random.seed(42)

    # ---------------------------------------------------------
    # SOLUTION: Create eigenvalues on the GPU
    # Generate (dim-1) random values, scale them, then combine with 1.0
    # ---------------------------------------------------------
    # SOLUTION: Generate weak eigenvalues using cp.random.random()
    weak_lam = cp.random.random(cfg.dim - 1) * (1.0 - cfg.dominance)

    # SOLUTION: Concatenate [1.0] with weak_lam using cp.concatenate and cp.array
    # Then permute them using cp.random.permutation
    lam = cp.random.permutation(cp.concatenate((cp.array([1.0]), weak_lam)))

    # ---------------------------------------------------------
    # SOLUTION: Construct the matrix A = P * D * P^-1 on the GPU
    # ---------------------------------------------------------
    # SOLUTION: Generate random matrix P using cp.random.random()
    P = cp.random.random((cfg.dim, cfg.dim))

    # SOLUTION: Create diagonal matrix D using cp.diag()
    D = cp.diag(cp.random.permutation(lam))

    # SOLUTION: Compute A = P @ D @ P^-1 using cp.linalg.inv()
    A = ((P @ D) @ cp.linalg.inv(P))

    return A

A_device = generate_device()

lam_est_device_gen = estimate_device(A_device)

np.testing.assert_allclose(lam_est_device_gen, 1, atol=1e-4)

print()
print("Dominant Eigenvalue:", lam_est_device_gen)

Step 0: residual = 2.346e+01
Step 10: residual = 2.859e-02
Step 20: residual = 2.984e-02
Step 30: residual = 1.433e-02
Step 40: residual = 5.035e-03
Step 50: residual = 1.643e-03
Step 60: residual = 5.309e-04
Step 70: residual = 1.726e-04
Step 80: residual = 5.663e-05
Step 90: residual = 1.875e-05
Step 100: residual = 6.253e-06
Step 110: residual = 2.098e-06
Step 120: residual = 7.077e-07
Step 130: residual = 2.396e-07
Step 140: residual = 8.140e-08
Step 150: residual = 2.772e-08
Step 160: residual = 9.461e-09
Step 170: residual = 3.234e-09
Step 180: residual = 1.107e-09
Step 190: residual = 3.792e-10
Step 200: residual = 1.299e-10
Step 210: residual = 4.469e-11

Dominant Eigenvalue: 0.9999999999549047


#### Think About It

Both functions use `seed(42)`. Are `A_host` and `A_device` identical? Try comparing them:

In [6]:
with np.printoptions(precision=4):
    print("A_host:")
    print(A_host)
    print()
    print("A_device:")
    print(A_device)
    print()

A_host:
[[-0.4937 -0.519  -0.2935 ... -0.1628  0.8361  0.531 ]
 [-1.0859  0.0087 -0.0661 ... -0.1706  1.0955  0.7075]
 [-0.4291 -0.3628  0.3393 ...  0.1813  0.2238 -0.2124]
 ...
 [-1.1089 -0.4564 -0.3024 ...  0.2075  1.2864  0.9066]
 [-0.8714 -0.5109 -0.1201 ... -0.072   1.3048  0.4372]
 [-1.6421 -0.6629 -0.2001 ... -0.2997  1.8579  1.5576]]

A_device:
[[-0.3175 -0.227   0.0765 ... -0.2411  0.9861 -0.6663]
 [-1.8135 -0.6378 -0.4466 ... -0.4503  3.2291 -1.3058]
 [-0.6443  0.3033  0.9719 ...  0.1302  0.4531 -0.3723]
 ...
 [-1.8697 -0.7714 -0.2048 ...  0.0244  2.859  -1.1147]
 [-1.1404 -0.9935 -0.4077 ... -0.2789  2.8553 -0.7879]
 [-0.5979 -0.6596  0.1047 ... -0.1826  1.4195 -0.0636]]



What does this reveal about `np.random` vs `cp.random`?

**SOLUTION:**

This reveals that `np.random` and `cp.random` use **different random number generator (RNG) implementations**, even with the same seed.

- NumPy uses the Mersenne Twister algorithm (or PCG64 in newer versions) on the CPU.
- CuPy uses a GPU-optimized RNG (typically XORWOW from cuRAND) that runs efficiently in parallel on thousands of GPU threads.

Even with the same seed value (`42`), these different algorithms produce completely different sequences of "random" numbers. This is why `A_host` and `A_device` contain different values.

**Key Takeaway:** If you need *identical* data on both CPU and GPU for verification purposes, you should:
1. Generate the data on one device (e.g., CPU with NumPy)
2. Transfer it to the other device (e.g., `cp.asarray(A_host)`)

This guarantees bit-for-bit identical data, which is essential for debugging and validation.

### 5. Verification and Benchmarking

Finally, let's verify our accuracy against a reference implementation (`numpy.linalg.eigvals()`) and benchmark the speedup.


In [7]:
start = time.perf_counter()
lam_ref = np.linalg.eigvals(A_host).real.max()
T_ref = time.perf_counter() - start

In [8]:
print(f"Power Iteration (Host)   = {lam_est_host}")
print(f"Power Iteration (Device) = {lam_est_device}")
print(f"`eigvals` Reference      = {lam_ref}")

rel_err_host   = abs(lam_est_host - lam_ref) / abs(lam_ref)
rel_err_device = abs(lam_est_device - lam_ref) / abs(lam_ref)
print()
print(f"Relative Error (Host)    = {rel_err_host:.3e}")
print(f"Relative Error (Device)  = {rel_err_device:.3e}")

np.testing.assert_allclose(lam_est_host, lam_ref, rtol=1e-4)
np.testing.assert_allclose(lam_est_device, lam_ref, rtol=1e-4)

Power Iteration (Host)   = 0.9999999999599408
Power Iteration (Device) = 0.9999999999591407
`eigvals` Reference      = 1.000000000000234

Relative Error (Host)    = 4.029e-11
Relative Error (Device)  = 4.109e-11


#### Benchmarking with `cupyx.profiler.benchmark()`

We use CuPy's built-in benchmarking utility for accurate GPU timing. This handles warmup and synchronization automatically.

We intentionally use `A_host` for both benchmarks, not `A_device`, because they're not the same matrices due to differences in NumPy and CuPy's random facilities. Different matrices converge at different rates, so it's only valid to benchmark on the same inputs.

In [9]:
cfg = PowerIterationConfig(progress=False)

print("Timing Host...")
T_host = cpx.profiler.benchmark(estimate_host, args=(A_host, cfg), n_repeat=10, n_warmup=1).cpu_times

print("Timing Device...")
T_device = cpx.profiler.benchmark(estimate_device, args=(A_host, cfg), n_repeat=10, n_warmup=1).cpu_times

print()
print(f"Power Iteration (Host)   = {T_host.mean() * 1000:.6g} ms ± {(T_host.std() / T_host.mean()):.2%} (mean ± relative stdev of {T_host.size} runs)")
print(f"Power Iteration (Device) = {T_device.mean() * 1000:.6g} ms ± {(T_device.std() / T_device.mean()):.2%} (mean ± relative stdev of {T_device.size} runs)")
print(f"`eigvals` Reference      = {T_ref * 1000:.6g} ms")

speedup = T_host.mean() / T_device.mean()
print()
print(f"Speedup (Device over Host) = {speedup:.1f}x")

Timing Host...
Timing Device...

Power Iteration (Host)   = 1342.18 ms ± 4.04% (mean ± relative stdev of 10 runs)
Power Iteration (Device) = 343.578 ms ± 3.54% (mean ± relative stdev of 10 runs)
`eigvals` Reference      = 33400.8 ms

Speedup (Device over Host) = 3.9x


---

### Extra Credit

**Explore the impact of changing the following parameters:**

1. **Problem Size (`dim`):** How does the GPU speedup change as you increase or decrease the matrix dimensions? Try values like 1024, 2048, 4096, 8192.

2. **Compute Workload (`max_steps` and `dominance`):** The `dominance` parameter controls how quickly the algorithm converges. A smaller dominance means eigenvalues are closer together, requiring more iterations. How does this affect the CPU vs GPU comparison?

3. **Check Frequency (`check_frequency`):** This controls how often we check for convergence (and trigger implicit CPU synchronization via the print statement). What happens to GPU performance when you check every step (`check_frequency=1`) vs. less frequently (`check_frequency=50`)?

**Experiment below:**

In [10]:
# Try different configurations here!
# Example:
# cfg_large = PowerIterationConfig(dim=8192, progress=False)
# cfg_slow_converge = PowerIterationConfig(dominance=0.01, progress=False)
# cfg_frequent_check = PowerIterationConfig(check_frequency=1, progress=True)

# Your experiments: